//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookningsSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeLogs
    {
        public int ChangeLogId { get; set; }
        public string PostInfo { get; set; }
        public System.DateTime ChangeDateTime { get; set; }
        public int UserId { get; set; }
        public string Action { get; set; }
    }
}
