//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookningsSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        public Requests()
        {
            this.RequestReservationResources = new HashSet<RequestReservationResources>();
            this.RequestReservationResources1 = new HashSet<RequestReservationResources>();
            this.Reservations = new HashSet<Reservations>();
        }
    
        public int RequestId { get; set; }
        public int RoomType_RoomTypeId { get; set; }
        public int City_CityId { get; set; }
        public System.DateTime RequestTime { get; set; }
        public int UserId { get; set; }
        public int QuantityPersons { get; set; }
        public Nullable<int> SizeArea { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public bool Reserved { get; set; }
        public bool Active { get; set; }
    
        public virtual Cities Cities { get; set; }
        public virtual ICollection<RequestReservationResources> RequestReservationResources { get; set; }
        public virtual ICollection<RequestReservationResources> RequestReservationResources1 { get; set; }
        public virtual ICollection<Reservations> Reservations { get; set; }
        public virtual RoomTypes RoomTypes { get; set; }
    }
}
