//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookningsSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservations
    {
        public Reservations()
        {
            this.RequestReservationResources = new HashSet<RequestReservationResources>();
        }
    
        public int ReservationId { get; set; }
        public int Request_RequestId { get; set; }
        public int User_CustomerId { get; set; }
        public int User_HandlerId { get; set; }
        public int Room_RoomId { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<RequestReservationResources> RequestReservationResources { get; set; }
        public virtual Requests Requests { get; set; }
        public virtual Users Users { get; set; }
    }
}
