//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookningsSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resources
    {
        public Resources()
        {
            this.RequestReservationResources = new HashSet<RequestReservationResources>();
        }
    
        public int ResourceId { get; set; }
        public int CityId { get; set; }
        public string ResourceName { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<RequestReservationResources> RequestReservationResources { get; set; }
    }
}
