//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookningsSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rooms
    {
        public int RoomId { get; set; }
        public int RoomTypeRoomTypeId { get; set; }
        public int City_CityId { get; set; }
        public int AreaSize { get; set; }
        public string StreetAddress { get; set; }
        public bool Active { get; set; }
        public int PreparationTime { get; set; }
    
        public virtual Cities Cities { get; set; }
        public virtual RoomTypes RoomTypes { get; set; }
    }
}
